spring.application.name=weather-api-robin
# Spring knows that it should load application-local.properties aswell :)
spring.profiles.active=local

weather.api.url=http://api.weatherapi.com/v1
weather.api.key=YOUR_API_KEY_HERE

activity.api.url=https://api.geoapify.com/v2
activity.api.key=YOUR_API_KEY_HERE

# My real API keys are stored in "application-local.properties" which is ignored by ".gitignore".
# This file only documents which properties are required. :)

# Circuit Breaker - weatherApi
resilience4j.circuitbreaker.instances.weatherApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.weatherApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.weatherApi.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.weatherApi.permitted-number-of-calls-in-half-open-state=3

# Circuit breaker - activityApi
resilience4j.circuitbreaker.instances.activityApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.activityApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.activityApi.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.activityApi.permitted-number-of-calls-in-half-open-state=3

# TimeLimiter - how long to wait for a response before timeout
resilience4j.timelimiter.instances.weatherApi.timeout-duration=5s
resilience4j.timelimiter.instances.activityApi.timeout-duration=5s