spring.application.name=weather-api-robin
# Spring knows that it should load application-local.properties aswell :)
spring.profiles.active=local

weather.api.url=http://api.weatherapi.com/v1
weather.api.key=YOUR_API_KEY_HERE

activity.api.url=https://api.geoapify.com/v2
activity.api.key=YOUR_API_KEY_HERE

# My real API keys are stored in "application-local.properties" which is ignored by ".gitignore".
# This file only documents which properties are required. :)